In [1]:
import pandas as pd

In [5]:
listings = pd.read_csv('listings.csv')
listings.head()
listings['neighbourhood'].unique()

array(['Hyde Park', 'West Town', 'Lincoln Park', 'Logan Square',
       'Edgewater', 'North Center', 'Pullman', 'Irving Park',
       'Near South Side', 'Near West Side', 'Kenwood', 'Lake View',
       'Lincoln Square', 'Forest Glen', 'West Ridge', 'Near North Side',
       'Lower West Side', 'East Garfield Park', 'Rogers Park',
       'North Lawndale', 'Uptown', 'Beverly', 'Woodlawn',
       'Grand Boulevard', 'South Lawndale', 'West Lawn', 'South Shore',
       'Mckinley Park', 'Dunning', 'Bridgeport', 'Humboldt Park', 'Loop',
       'West Garfield Park', 'Portage Park', 'Hegewisch', 'Avondale',
       'Armour Square', 'Jefferson Park', 'Ashburn', 'Douglas',
       'Greater Grand Crossing', 'Norwood Park', 'Garfield Ridge',
       'Austin', 'Hermosa', 'Belmont Cragin', 'Oakland', 'West Pullman',
       'Archer Heights', 'North Park', 'Brighton Park', 'Albany Park',
       'Englewood', 'West Englewood', 'Montclare', 'Chatham',
       'Calumet Heights', 'Fuller Park', 'Auburn Gresham', 'Edison Park',
       'Ohare', 'New City', 'Morgan Park', 'Washington Park',
       'South Deering', 'South Chicago', 'Chicago Lawn',
       'Washington Heights', 'Roseland', 'East Side', 'Clearing',
       'Mount Greenwood', 'West Elsdon', 'Gage Park', 'Burnside',
       'Avalon Park'], dtype=object)

In [3]:
reviews = pd.read_csv('reviews.csv')
reviews.head()

   listing_id        date
0        2384  2015-01-09
1        2384  2015-03-24
2        2384  2015-04-30
3        2384  2015-05-04
4        2384  2015-05-10

In [4]:
neighbourhoods = pd.read_csv('neighbourhoods.csv')
neighbourhoods.head()

   neighbourhood_group   neighbourhood
0                  NaN     Albany Park
1                  NaN  Archer Heights
2                  NaN   Armour Square
3                  NaN         Ashburn
4                  NaN  Auburn Gresham

In [ ]:
listing